# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'app_ios' do
	use_frameworks!
  flutter_application_path = '../app_flutter'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end